name: Update Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout master"
        uses: actions/checkout@v2
        with:
          ref: master
      - name: "Update master branch"
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: Anuken/Mindustry
          upstream_branch: master
          target_branch: master
          git_pull_args: --ff-only
      - name: "."
        run: git remote remove upstream
      - name: "Checkout me-things"
        uses: actions/checkout@v2
        with:
          ref: me-things
      - name: "Update me-things branch"
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: Blockzilla101/Mindustry
          upstream_branch: master
          target_branch: me-things
