name: Update Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout master"
        uses: actions/checkout@v2
        with:
          ref: master
      - name: "Update master branch"
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git remote show upstream &> /dev/null || git remote add upstream "https://github.com/Anuken/Mindustry.git"
          if [ $(git branch --show-current) != "master" ]; then
            git checkout master
            echo "Checkedout master branch"
          fi
          git fetch upstream master
          localhash=$(git rev-parse master)
          upstreamhash=$(git rev-parse upstream/master)
          if [ "${localhash}" != "${upstreamhash}" ]; then
            echo "Found new commits"
            git log upstream/master ${localhash}..HEAD --pretty=oneline
            echo "Updating"
            git pull --no-edit --ff-only upstream master
            git push origin master
            echo "foundCommits=yes" >> $GITHUB_ENV
          else
            echo "foundCommits=no" >> $GITHUB_ENV
            echo "No new commits found"
          fi
      - name: "Checkout me-things"
        uses: actions/checkout@v2
        with:
          ref: me-things
          fetch-depth: 0
      - name: "Update me-things branch"
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "{{ github.actor }}@users.noreply.github.com"
          git pull --no-edit upstream master
          git push origin me-things
