name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - me-things

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger BE build
      if: ${{ github.repository == 'Blockzilla101/Mindustry' }}
      run: |
        git clone --depth=1 --branch=master https://github.com/Blockzilla101/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        version=$(( `git tag --sort=committerdate | tail -1` + 1 ))
        echo "BE Version = ${version}"
        git tag ${version}
        git config --global user.name "Build Uploader"
        git push https://Blockzilla101:${{ secrets.API_TOKEN_GITHUB }}@github.com/Blockzilla101/MindustryBuilds ${version}
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Run unit tests
      run: ./gradlew clean cleanTest test
