name: Build

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run unit tests
        run: ./gradlew clean cleanTest test --stacktrace

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: build
        run: ./gradlew pack desktop:dist android:assembleDebug
      - name: upload desktop jar
        uses: actions/upload-artifact@v2
        with:
          name: Mindustry.jar
          path: desktop/build/libs/Mindustry.jar
      - name: upload android apk
        uses: actions/upload-artifact@v2
        with:
          name: Mindustry.apk
          path: android/build/outputs/apk/debug/android-debug.apk
